import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "مرحباً",
          "2": "أختر لغتك",
          "3": "عربي",
          "4": "انجليزي",
          "5": "ألماني",
          "6": "أسباني",
          "7": "ضيف لغة يا ملك",
          "8": "أختر منتجاً",
          "9": "هيا متجرنا يفتح لك الافاق في عالم امن مليئ ومتنوع بكل ما تحب",
          "10": "صباح الفل ياملك التطبيق بتاعنا جامد اخر جمدان",
          "11": "اتقل وتاخد حاجة نضيفة",
          "12": "صلي علي النبي ومتقلقش من حاجة",
          "13": "التالي",
          "14": "الدخول",
          "15": "سجل الدخول باستخدام بريدك الاكتروني\n وكلمة السر الخاصة بك",
          "16": "",
          "17": "تفحص بريدك الاكتروني لقدر ارسلنا كود الي ",
          "18": "تم تغيير كلمة المرور بنحاح",
          "19": "الان بامكانك تسجيل الدخول",
          "20": "نسيت كلمة المرور",
          "21": "تذكرني",
          "22": "تسجيل الدخول",
          "23": "البريد الالكتروني",
          "24": "كلمة المرور",
          "25": "تم التحقق من بريدك الاكتروني",
          "26": "الان بامكانك تسجيل الدخول",
          "27": "أكتب بريدك الالكتروني",
          "28": "اكتب كلمة مرور",
          "29": "أعد كتابة كلمة المرور",
          "30": "أكتب رقم تلفونك",
          "31": "أكتب كلمة مرور جديدة",
          "32": "رقم التليفون",
          "33": "كلمة مرور جديدة",
          "34": "تأكيد كلمة المرور",
          "35": "أدخل اسمك",
          "36": "الأسم",
          "37": "انشاء الحساب",
          "38": " أليس لديك حساب ؟",
          "39": " إذا كان لديك حساب قم ب",
          "40":
              "انشأ حساب ببياناتك الشخصية او قم بانشاء \n الحساب باستخدام مواقع التواصل",
          "41": "ص/n",
        },
        "en": {
          "1": "Welcome",
          "2": "Choose Your Language",
          "3": "arabic",
          "4": "english",
          "5": "german",
          "6": "spain",
          "7": "german",
          "8": "Choose Product",
          "9": "Let's go our store open the world for all you love",
          "10": " the world wait you",
          "11": "fantastic",
          "12": "very very fantasic , trust me my bro",
          "13": "next",
          "14": "Enter",
          "15":
              "Sign in with your email and password\n or Continue  with social media",
          "16": "",
          "17": "check your email , we send a verification code to ",
          "18": "Password Changed Successfully",
          "19": "now , you can login",
          "20": "Forget Password",
          "21": "remember me",
          "22": "Login",
          "23": "Email",
          "24": "Password",
          "25": "Your Email Verified Successfully",
          "26": "now , you can login",
          "27": "Enter Your Email",
          "28": "Enter Your Password",
          "29": "Confirm Your Password",
          "30": "Enter Your Phone",
          "31": "Enter Your New Password",
          "32": "Phone",
          "33": "New Password",
          "34": "Confirm Password",
          "35": "Enter Your User Name",
          "36": "User Name",
          "37": "Sign Up",
          "38": "Dont't have an account ? ",
          "39": "if you have an account go to ",
          "40":
              "Sign Up with your information \n or Singn uP  with social media",
          "41": "if you have an account go to ",
        },
        "de": {
          "1": "Willkommen",
          "2": "Wählen Sie Ihre Sprache",
          "3": "arabisch",
          "4": "englisch",
          "5": "deutsch",
          "6": "spanisch",
          "7": "deutsch",
          "8": "Wählen Sie ein Produkt",
          "9": "Wählen Sie ein Produkt",
        },
      };
}
