import 'package:ecommerceapp/core/constants/lang_keys.dart';
import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          // main
          LangKeys.appTitle: "تطبيقي",
          LangKeys.offersTitle: "العروض",

          // onboarding
          LangKeys.chooseLanguage: "اختر لغتك",
          LangKeys.arabic: "العربية",
          LangKeys.english: "الإنجليزية",
          LangKeys.germany: "الألمانية",
          LangKeys.spain: "الإسبانية",
          LangKeys.chooseProduct: "اختر منتجًا",
          LangKeys.onBoarding1: "مرحبًا بك في التطبيق",
          LangKeys.onBoardingTitle1: "ابدأ معنا",
          LangKeys.onBoardingTitle2: "اكتشف المزيد",
          LangKeys.onBoardingTitle3: "استمتع بالتجربة",
          LangKeys.onBoardingBody1: "هذا هو الشرح الأول للبدء.",
          LangKeys.onBoardingBody2: "تعرف على ميزات التطبيق.",
          LangKeys.onBoardingBody3: "استخدم التطبيق بسهولة.",
          LangKeys.next: "التالي",
          LangKeys.enter: "دخول",

          // auth
          LangKeys.login: "تسجيل الدخول",
          LangKeys.loginTitle: "مرحبا بعودتك",
          LangKeys.loginSub:
              "سجل الدخول باستخدام بريدك الإلكتروني وكلمة المرور",
          LangKeys.signup: "إنشاء حساب",
          LangKeys.signupTitle: "انضم إلينا الآن",
          LangKeys.signupSub: "سجل بياناتك لإنشاء حساب جديد",
          LangKeys.rememberMe: "تذكرني",
          LangKeys.forgetPassword: "نسيت كلمة المرور؟",
          LangKeys.dontHaveAccount: " ليس لديك حساب ؟  ",
          LangKeys.ifHaveAccount: "إذا كان لديك حساب، سجل الدخول",
          LangKeys.email: "البريد الإلكتروني",
          LangKeys.emailFieldHint: "أدخل بريدك الإلكتروني",
          LangKeys.password: "كلمة المرور",
          LangKeys.passwordFieldHint: "أدخل كلمة المرور",
          LangKeys.userName: "اسم المستخدم",
          LangKeys.userNameFieldHint: "أدخل اسم المستخدم",
          LangKeys.phone: "رقم الهاتف",
          LangKeys.phoneFieldHint: "أدخل رقم الهاتف",
          LangKeys.confirmPassword: "تأكيد كلمة المرور",
          LangKeys.confirmHint: "أعد إدخال كلمة المرور",
          LangKeys.emptyFieldError: "هذا الحقل لا يمكن أن يكون فارغًا",
          LangKeys.minLengthError: "الحد الأدنى لطول النص غير مستوفى",
          LangKeys.maxLengthError: "تجاوز الحد الأقصى لطول النص",
          LangKeys.checkYourEmail: "تحقق من بريدك الإلكتروني",
          LangKeys.check: "تحقق",
          LangKeys.returnTo: "العودة إلى",
          LangKeys.verificationCode: "كود التحقق",
          LangKeys.verificationSentence:
              "أدخل كود التحقق المرسل إلى بريدك الإلكتروني",
          LangKeys.continueButton: "استمرار",
          LangKeys.newPassword: "كلمة المرور الجديدة",
          LangKeys.resetPassword: "إعادة تعيين كلمة المرور",
          LangKeys.resetPasswordSentence: "أدخل كلمة المرور الجديدة لتحديثها",
          LangKeys.save: "حفظ",

          // homepage
          LangKeys.searchFieldHint: "ابحث عن منتج...",
          LangKeys.specialForYou: "عروض خاصة لك",
          LangKeys.seeAll: "عرض الكل",
          LangKeys.categories: "الفئات",
          LangKeys.topSelling: "الأكثر مبيعًا",
          LangKeys.offers: "العروض",
          LangKeys.cart: "السلة",
          LangKeys.profile: "حسابي",
          LangKeys.settings: "الإعدادات",

          // cart
          LangKeys.cartTitle: "السلة",
          LangKeys.couponFiledHint: "أدخل كود القسيمة",
          LangKeys.apply: "تطبيق",
          LangKeys.checkoutButton: "الدفع",
          LangKeys.cartTotal: "إجمالي السلة",
          LangKeys.deliveryCost: "تكلفة التوصيل",
          LangKeys.total: "الإجمالي",

          // checkout
          LangKeys.checkoutTitle: "الدفع",
          LangKeys.deliveryMethod: "طريقة التوصيل",
          LangKeys.delivery: "توصيل",
          LangKeys.receiveFromStore: "استلام من المتجر",
          LangKeys.address: "العنوان",
          LangKeys.paymentMethod: "طريقة الدفع",
          LangKeys.cash: "نقدًا",
          LangKeys.creditCards: "بطاقات الائتمان",

          // profile
          LangKeys.orders: "الطلبات",
          LangKeys.ordersSub: "قائمة طلباتك",
          LangKeys.information: "المعلومات الشخصية",
          LangKeys.informationSub: "تحديث بياناتك",
          LangKeys.addresses: "العناوين",
          LangKeys.addressesSub: "إدارة عناوينك",

          // address
          LangKeys.choosingLocationTitle1: "اختر موقع العنوان",
          LangKeys.choosingLocationTitle2: "حدد موقعك بدقة",
          LangKeys.addressName: "اسم العنوان",
          LangKeys.selectGov: "اختر المحافظة",
          LangKeys.selectCity: "اختر المدينة",
          LangKeys.streetName: "اسم الشارع",
          LangKeys.add: "إضافة",

          // orders
          LangKeys.pendingOrders: "الطلبات المعلقة",
          LangKeys.orderNumber: "رقم الطلب",
          LangKeys.totalPrice: "السعر الإجمالي",
          LangKeys.details: "تفاصيل",
          LangKeys.delete: "حذف",
          LangKeys.archiveOrders: "الأرشيف",

          // settings
          LangKeys.settingsTitle: "الإعدادات",
          LangKeys.language: "اللغة",
          LangKeys.languageSub: "اختر لغتك المفضلة",
          LangKeys.notification: "الإشعارات",
          LangKeys.notificationSub: "إدارة الإشعارات",
          LangKeys.theme: "الثيم",
          LangKeys.themeSub: "اختر نمط التطبيق",
          LangKeys.aboutUs: "من نحن",
          LangKeys.aboutUsSub: "معلومات عن التطبيق",
          LangKeys.contactUs: "اتصل بنا",
          LangKeys.contactUsSub: "نرحب بملاحظاتك",
          LangKeys.logOut: "تسجيل خروج",
          LangKeys.logOutSub: "تسجيل خروج من التطبيق",

          // dialog
          LangKeys.warn: "تحذير",
          LangKeys.deleteConfirmMsg: "هل أنت متأكد من حذف هذا العنصر؟",
          LangKeys.ok: "حسناً",
          LangKeys.cancel: "إلغاء",
          LangKeys.confirm: "تأكيد",
          LangKeys.logoutConfirmMsg: "هل تريد تسجيل الخروج؟",
          LangKeys.exitMsg: "هل أنت متأكد من الخروج؟",
          LangKeys.exit: "خروج",
        },
        "en": {
          // main
          LangKeys.appTitle: "My App",
          LangKeys.offersTitle: "Offers",

          // onboarding
          LangKeys.chooseLanguage: "Choose Your Language",
          LangKeys.arabic: "Arabic",
          LangKeys.english: "English",
          LangKeys.germany: "German",
          LangKeys.spain: "Spanish",
          LangKeys.chooseProduct: "Choose Product",
          LangKeys.onBoarding1: "Welcome to the app",
          LangKeys.onBoardingTitle1: "Get Started",
          LangKeys.onBoardingTitle2: "Discover More",
          LangKeys.onBoardingTitle3: "Enjoy the Experience",
          LangKeys.onBoardingBody1: "This is the first step to start.",
          LangKeys.onBoardingBody2: "Learn about app features.",
          LangKeys.onBoardingBody3: "Use the app easily.",
          LangKeys.next: "Next",
          LangKeys.enter: "Enter",

          // auth
          LangKeys.login: "Login",
          LangKeys.loginTitle: "Welcome Back",
          LangKeys.loginSub: "Sign in with your email and password",
          LangKeys.signup: "Sign Up",
          LangKeys.signupTitle: "Join Us Now",
          LangKeys.signupSub: "Register your information",
          LangKeys.rememberMe: "Remember Me",
          LangKeys.forgetPassword: "Forgot Password?",
          LangKeys.dontHaveAccount: "Don't have an account? ",
          LangKeys.ifHaveAccount: "If you have an account, login",
          LangKeys.email: "Email",
          LangKeys.emailFieldHint: "Enter your email",
          LangKeys.password: "Password",
          LangKeys.passwordFieldHint: "Enter your password",
          LangKeys.userName: "User Name",
          LangKeys.userNameFieldHint: "Enter your user name",
          LangKeys.phone: "Phone",
          LangKeys.phoneFieldHint: "Enter your phone number",
          LangKeys.confirmPassword: "Confirm Password",
          LangKeys.confirmHint: "Re-enter your password",
          LangKeys.emptyFieldError: "This field cannot be empty",
          LangKeys.minLengthError: "Minimum length not met",
          LangKeys.maxLengthError: "Maximum length exceeded",
          LangKeys.checkYourEmail: "Check your email",
          LangKeys.check: "Check",
          LangKeys.returnTo: "Return to",
          LangKeys.verificationCode: "Verification Code",
          LangKeys.verificationSentence:
              "Enter the verification code sent to your email",
          LangKeys.continueButton: "Continue",
          LangKeys.newPassword: "New Password",
          LangKeys.resetPassword: "Reset Password",
          LangKeys.resetPasswordSentence: "Enter a new password to reset",
          LangKeys.save: "Save",

          // homepage
          LangKeys.searchFieldHint: "Search for product...",
          LangKeys.specialForYou: "Special For You",
          LangKeys.seeAll: "See All",
          LangKeys.categories: "Categories",
          LangKeys.topSelling: "Top Selling",
          LangKeys.offers: "Offers",
          LangKeys.cart: "Cart",
          LangKeys.profile: "Profile",
          LangKeys.settings: "Settings",

          // cart
          LangKeys.cartTitle: "Cart",
          LangKeys.couponFiledHint: "Enter coupon code",
          LangKeys.apply: "Apply",
          LangKeys.checkoutButton: "Checkout",
          LangKeys.cartTotal: "Cart Total",
          LangKeys.deliveryCost: "Delivery Cost",
          LangKeys.total: "Total",

          // checkout
          LangKeys.checkoutTitle: "Checkout",
          LangKeys.deliveryMethod: "Delivery Method",
          LangKeys.delivery: "Delivery",
          LangKeys.receiveFromStore: "Receive from Store",
          LangKeys.address: "Address",
          LangKeys.paymentMethod: "Payment Method",
          LangKeys.cash: "Cash",
          LangKeys.creditCards: "Credit Cards",

          // profile
          LangKeys.orders: "Orders",
          LangKeys.ordersSub: "Your Orders List",
          LangKeys.information: "Information",
          LangKeys.informationSub: "Update your info",
          LangKeys.addresses: "Addresses",
          LangKeys.addressesSub: "Manage your addresses",

          // address
          LangKeys.choosingLocationTitle1: "Choose Location",
          LangKeys.choosingLocationTitle2: "Select your precise location",
          LangKeys.addressName: "Address Name",
          LangKeys.selectGov: "Select Governorate",
          LangKeys.selectCity: "Select City",
          LangKeys.streetName: "Street Name",
          LangKeys.add: "Add",

          // orders
          LangKeys.pendingOrders: "Pending Orders",
          LangKeys.orderNumber: "Order Number",
          LangKeys.totalPrice: "Total Price",
          LangKeys.details: "Details",
          LangKeys.delete: "Delete",
          LangKeys.archiveOrders: "Archive Orders",

          // settings
          LangKeys.settingsTitle: "Settings",
          LangKeys.language: "Language",
          LangKeys.languageSub: "Choose your preferred language",
          LangKeys.notification: "Notification",
          LangKeys.notificationSub: "Manage notifications",
          LangKeys.theme: "Theme",
          LangKeys.themeSub: "Choose app theme",
          LangKeys.aboutUs: "About Us",
          LangKeys.aboutUsSub: "Information about app",
          LangKeys.contactUs: "Contact Us",
          LangKeys.contactUsSub: "We welcome your feedback",
          LangKeys.logOut: "Log Out",
          LangKeys.logOutSub: "Sign out from app",

          // dialog
          LangKeys.warn: "Warning",
          LangKeys.deleteConfirmMsg:
              "Are you sure you want to delete this item?",
          LangKeys.ok: "OK",
          LangKeys.cancel: "Cancel",
          LangKeys.confirm: "Confirm",
          LangKeys.logoutConfirmMsg: "Do you want to log out?",
          LangKeys.exitMsg: "Do you want to exit ?",
          LangKeys.exit: "exit",
        },
      };
}
