// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-kzJxTN2BTHu7U2QQqklUr5HCqmNF3Hk',
    appId: '1:594430632741:web:d3af72de7bd36ed52eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    authDomain: 'ecommerce-9d588.firebaseapp.com',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
    measurementId: 'G-N4ZQF5DMKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2aAlES3d6Hxf1XPiEGN4jE2fGtk_tGY',
    appId: '1:594430632741:android:61b043b035aa69692eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Ko3eXNMHnzTodVXr5lIR1XQwsQh9o7k',
    appId: '1:594430632741:ios:193f2792f08184792eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QDXTrq-xYVWTNz6LWjGwCg5ZUKZL1hI',
    appId: '1:913003752431:ios:61499ba35b744479d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrC7gpVffPRV3QC8_uoe3Sfng8DIqlTPg',
    appId: '1:913003752431:web:4402bea5b2e1ff56d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    authDomain: 'adminecommerce-13fac.firebaseapp.com',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
    measurementId: 'G-YSR3H12ZYD',
  );

}