// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrC7gpVffPRV3QC8_uoe3Sfng8DIqlTPg',
    appId: '1:913003752431:web:a07216b2fa31dbb2d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    authDomain: 'adminecommerce-13fac.firebaseapp.com',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
    measurementId: 'G-8H5L1WE0ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbBcPX5B3SSDY81wSgCXeko9IJJbNNik',
    appId: '1:913003752431:android:3ec87dc44f199be5d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QDXTrq-xYVWTNz6LWjGwCg5ZUKZL1hI',
    appId: '1:913003752431:ios:a7cf59755ba1f895d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QDXTrq-xYVWTNz6LWjGwCg5ZUKZL1hI',
    appId: '1:913003752431:ios:61499ba35b744479d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrC7gpVffPRV3QC8_uoe3Sfng8DIqlTPg',
    appId: '1:913003752431:web:4402bea5b2e1ff56d3641a',
    messagingSenderId: '913003752431',
    projectId: 'adminecommerce-13fac',
    authDomain: 'adminecommerce-13fac.firebaseapp.com',
    storageBucket: 'adminecommerce-13fac.firebasestorage.app',
    measurementId: 'G-YSR3H12ZYD',
  );

}